all:
  exclude:
    - 'spec/**/*'
# exclude files for single runner
eslint:
  exclude:
    - 'app/assets/**/*'
github:
  slug: prontolabs/pronto
max_warnings: 150
warnings_per_review: 30
verbose: false
runners: [rails_schema] # only listed runners will be executed
skip_runners: [] # all, except listed runners will be executed